"""Adiciona relacionamento de sistema em funcao

Revision ID: 195ba882f733
Revises: 53c8b14a48fe
Create Date: 2025-08-22 14:27:57.048429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195ba882f733'
down_revision: Union[str, Sequence[str], None] = '53c8b14a48fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcao', sa.Column('sistema_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'funcao', 'sistema', ['sistema_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funcao', type_='foreignkey')
    op.drop_column('funcao', 'sistema_id')
    # ### end Alembic commands ###
