"""Adiciona campo qtde de inm

Revision ID: 448d4c0f9595
Revises: 195ba882f733
Create Date: 2025-08-22 15:04:36.667382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448d4c0f9595'
down_revision: Union[str, Sequence[str], None] = '195ba882f733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcao', sa.Column('qtd_inm', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcao', 'qtd_inm')
    # ### end Alembic commands ###
