"""Adiciona relacionamento de sistema em contagem

Revision ID: 53c8b14a48fe
Revises: 61ce9024e214
Create Date: 2025-08-21 10:55:27.634541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c8b14a48fe'
down_revision: Union[str, Sequence[str], None] = '61ce9024e214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contagem', sa.Column('sistema_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contagem', 'sistema', ['sistema_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contagem', type_='foreignkey')
    op.drop_column('contagem', 'sistema_id')
    # ### end Alembic commands ###
