"""Adiciona campos de calculo em funcao

Revision ID: a9cc79d9ecc2
Revises: 448d4c0f9595
Create Date: 2025-08-22 15:19:18.993789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cc79d9ecc2'
down_revision: Union[str, Sequence[str], None] = '448d4c0f9595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcao', sa.Column('complexidade', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('funcao', sa.Column('ponto_de_funcao_bruto', sa.Integer(), nullable=True))
    op.add_column('funcao', sa.Column('ponto_de_funcao_liquido', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcao', 'ponto_de_funcao_liquido')
    op.drop_column('funcao', 'ponto_de_funcao_bruto')
    op.drop_column('funcao', 'complexidade')
    # ### end Alembic commands ###
