"""Cria tabelas de contagem e funcao

Revision ID: b77c796deae5
Revises: 90b6bab5d63e
Create Date: 2025-08-21 09:37:49.234356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b77c796deae5'
down_revision: Union[str, Sequence[str], None] = '90b6bab5d63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tipo_contagem', sa.Enum('ESTIMATIVA', 'INDICATIVA', 'DETALHADA', name='tipocontagemenum'), nullable=False),
    sa.Column('metodo_contagem', sa.Enum('NESMA', 'IFPUG', 'COSMIC', name='metodocontagemenum'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('responsavel', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('funcionalidade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tipo_funcao', sa.Enum('ALI', 'AIE', 'EE', 'CE', 'SE', name='tipofuncaoenum'), nullable=False),
    sa.Column('qtd_der', sa.Integer(), nullable=False),
    sa.Column('qtd_rlr', sa.Integer(), nullable=False),
    sa.Column('desc_der', sa.Text(), nullable=True),
    sa.Column('desc_rlr', sa.Text(), nullable=True),
    sa.Column('insumos', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('contagem_id', sa.Integer(), nullable=False),
    sa.Column('fator_ajuste_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contagem_id'], ['contagem.id'], ),
    sa.ForeignKeyConstraint(['fator_ajuste_id'], ['fatorajuste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcao_nome'), 'funcao', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funcao_nome'), table_name='funcao')
    op.drop_table('funcao')
    op.drop_table('contagem')
    # ### end Alembic commands ###
