"""Cria a tabela de fatores de ajuste

Revision ID: dc46a580a1f7
Revises: faab5e59c3ef
Create Date: 2025-08-20 16:45:25.265818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc46a580a1f7'
down_revision: Union[str, Sequence[str], None] = 'faab5e59c3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatorajuste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fator', sa.Float(), nullable=False),
    sa.Column('tipo_ajuste', sa.Enum('PERCENTUAL', 'UNITARIO', name='tipoajuste'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fatorajuste_nome'), 'fatorajuste', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fatorajuste_nome'), table_name='fatorajuste')
    op.drop_table('fatorajuste')
    # ### end Alembic commands ###
